In [3]:
import nltk                    #natural language tool-kit

In [1]:
A = "This is an awesome movie, Loved it" -  posistive

In [2]:
B = "What a waste of time" - negative

In [ ]:
Sentiment Analysis

In [ ]:
Suggest me some good movies

In [5]:
# nltk.download()

In [4]:
passage=""" The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. The films are based on characters that appear in American comic books published by Marvel Comics. The franchise also includes television series, short films, digital series, and literature. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.

Marvel Studios releases its films in groups called "Phases", with the first three phases collectively known as "The Infinity Saga" and the following three phases as "The Multiverse Saga". The first MCU film, Iron Man (2008), began Phase One, which culminated in the 2012 crossover film The Avengers. Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America: Civil War (2016) and concluded with Spider-Man: Far From Home (2019). Phase Four began with Black Widow (2021) and concluded with Black Panther: Wakanda Forever (2022). Ant-Man and the Wasp: Quantumania (2023) began Phase Five, which will end with Thunderbolts (2025), and Phase Six will begin with The Fantastic Four (2025). Phase Six and "The Multiverse Saga" will conclude with Avengers 5 (2026) and Avengers: Secret Wars (2027).

Marvel Television expanded the universe to network television with Agents of S.H.I.E.L.D. on ABC in 2013 before further expanding to streaming television on Netflix and Hulu and to cable television on Freeform. They also produced the digital series Agents of S.H.I.E.L.D.: Slingshot. Marvel Studios began producing their own television series for streaming on Disney+, starting with WandaVision in 2021 as the beginning of Phase Four. They also expanded to television specials in Phase Four, known as Marvel Studios Special Presentations, the first of which was Werewolf by Night (2022). The MCU also includes tie-in comics published by Marvel Comics, a series of direct-to-video short films called Marvel One-Shots, and viral marketing campaigns for the films featuring the faux news programs WHIH Newsfront and The Daily Bugle.

The franchise has been commercially successful, becoming one of the highest-grossing media franchises of all time, and generally received positive reviews. It has inspired other film and television studios to attempt similar shared universes and has also inspired several themed attractions, an art exhibit, television specials, literary material, multiple tie-in video games, and commercials."""

In [5]:
passage  #in NLP we are calling it corpus

' The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. The films are based on characters that appear in American comic books published by Marvel Comics. The franchise also includes television series, short films, digital series, and literature. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.\n\nMarvel Studios releases its films in groups called "Phases", with the first three phases collectively known as "The Infinity Saga" and the following three phases as "The Multiverse Saga". The first MCU film, Iron Man (2008), began Phase One, which culminated in the 2012 crossover film The Avengers. Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America: Civil War (2016) and concluded with Spider-Man: Far From Home (2019). Pha

In [6]:
len(passage)

2582

# Tokenization

1:Sentence Tokenization


2: Word Tokenization

In [7]:
sentences = nltk.sent_tokenize(passage)

In [8]:
len(sentences)

20

In [9]:
sentences

[' The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios.',
 'The films are based on characters that appear in American comic books published by Marvel Comics.',
 'The franchise also includes television series, short films, digital series, and literature.',
 'The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.',
 'Marvel Studios releases its films in groups called "Phases", with the first three phases collectively known as "The Infinity Saga" and the following three phases as "The Multiverse Saga".',
 'The first MCU film, Iron Man (2008), began Phase One, which culminated in the 2012 crossover film The Avengers.',
 'Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015).',
 'Phase Three began with Captain America: Civil War (2016) and concluded with Spider-Man:

In [10]:
words=nltk.word_tokenize(passage)

In [11]:
len(words)

479

In [12]:
words

['The',
 'Marvel',
 'Cinematic',
 'Universe',
 '(',
 'MCU',
 ')',
 'is',
 'an',
 'American',
 'media',
 'franchise',
 'and',
 'shared',
 'universe',
 'centered',
 'on',
 'a',
 'series',
 'of',
 'superhero',
 'films',
 'produced',
 'by',
 'Marvel',
 'Studios',
 '.',
 'The',
 'films',
 'are',
 'based',
 'on',
 'characters',
 'that',
 'appear',
 'in',
 'American',
 'comic',
 'books',
 'published',
 'by',
 'Marvel',
 'Comics',
 '.',
 'The',
 'franchise',
 'also',
 'includes',
 'television',
 'series',
 ',',
 'short',
 'films',
 ',',
 'digital',
 'series',
 ',',
 'and',
 'literature',
 '.',
 'The',
 'shared',
 'universe',
 ',',
 'much',
 'like',
 'the',
 'original',
 'Marvel',
 'Universe',
 'in',
 'comic',
 'books',
 ',',
 'was',
 'established',
 'by',
 'crossing',
 'over',
 'common',
 'plot',
 'elements',
 ',',
 'settings',
 ',',
 'cast',
 ',',
 'and',
 'characters',
 '.',
 'Marvel',
 'Studios',
 'releases',
 'its',
 'films',
 'in',
 'groups',
 'called',
 '``',
 'Phases',
 "''",
 ',',
 'wi

# Stopwords

Whenever we are working with any text data then we have to remove the  stopwords from the text because these stop words does not add any specific value to the actual information of the text.


Eg: Jacob is an intelligent person.

stopwords:  is an

Jacob intelligent person

In [13]:
"""
The food was bad, I want my refund.

food bad want refund


Applying
applied
apply

apply

going
goes
gone

go




"""

''

In [15]:
from nltk.corpus import stopwords

In [16]:
stopwords.words('english')
# stopwords.words('german')
# stopwords.words('spanish')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

# Stemming

In [24]:
stemmer = nltk.PorterStemmer()

In [ ]:
len(sentences)

In [ ]:
sentences[0]

In [ ]:
nltk.word_tokenize(sentences[0])

In [ ]:
#list comprehension

#[operation   for loop on the list   if condition]

In [ ]:
even = []
for i in range(21):
    if i %2==0:
        even.append(i*5)
print(even)
        

In [ ]:
even_list = [i*5 for i in range(21) if i%2==0]

In [ ]:
even_list

In [ ]:
words_list=nltk.word_tokenize(sentences[0])

In [ ]:
words_list

In [ ]:
" ".join(words_list)

In [ ]:
ls=["Disney", "DC", "DreamWorks"]

In [ ]:
word="marvel"
if word in set(ls):
    print("Word is not present")
else:
    print("Word is present")

In [ ]:
[stemmer.stem(word) for word in words_list if word not in set(stopwords.words('english'))]

In [25]:
stem_sentences = nltk.sent_tokenize(passage)

In [26]:
for i in range(len(stem_sentences)): #0
    words_list = nltk.word_tokenize(stem_sentences[i])
    words = [stemmer.stem(word) for word in words_list if word not in set(stopwords.words('english'))]
    stem_sentences[i] = ' '.join(words)

In [ ]:
# stem_sentences

In [ ]:
sentences

# Lemmatization

In [9]:
lemma_sentences=nltk.sent_tokenize(passage)

In [10]:
from nltk.stem import WordNetLemmatizer

In [11]:
lemmatizer=WordNetLemmatizer()

In [12]:
for i in range(len(lemma_sentences)):
    words_list = nltk.word_tokenize(lemma_sentences[i])
    words = [lemmatizer.lemmatize(word) for word in words_list if word not in set(stopwords.words("english"))]
    lemma_sentences[i] = " ".join(words)
    

In [ ]:
print("Actual Sentence: \n", sentences[0])
print("\n\nStemming Sentence: \n", stem_sentences[0])
print("\n\nLemmatized Sentence: \n", lemma_sentences[0])

# Removal of the punctuation

In [18]:
import re 

In [ ]:
text= sentences[0]

In [17]:
text="Hey ! Wassup!, it doesn't sound good to me. Can you give me $500 ? "

In [16]:
text

"Hey ! Wassup!, it doesn't sound good to me. Can you give me $500 ? "

In [19]:
text=re.sub('[^$a-zA-Z0-9]', ' ', text)
text

'Hey   Wassup   it doesn t sound good to me  Can you give me $500   '

In [ ]:
text.lower()

In [22]:
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z0-9]', ' ', sentences[i])            #removal of the punctuation
    
    review=review.lower()             # convert the sentencce into the lowercase
    
    review=review.split()         #split is creating a list of words of sentence/ you can use word tokenizer
    
    review=[lemmatizer.lemmatize(word) for word in review if word not in stopwords.words('english')]
    
    review=' '.join(review)
    
    corpus.append(review)

In [28]:
print("Actual Sentence: \n", sentences[0])
print("\n\nStemming Sentence: \n", stem_sentences[0])
print("\n\nLemmatized Sentence: \n", lemma_sentences[0])
print("\n\nLemmatized v2 Sentence: \n", corpus[0])

Actual Sentence: 
  The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios.


Stemming Sentence: 
 the marvel cinemat univers ( mcu ) american media franchis share univers center seri superhero film produc marvel studio .


Lemmatized Sentence: 
  The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios.


Lemmatized v2 Sentence: 
 marvel cinematic universe mcu american medium franchise shared universe centered series superhero film produced marvel studio


# Vectorization


1: bag of words

2: TF-IDF (Term Frequeny - Inverse Document Frequency)

# Bag of Words 

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
# cv=CountVectorizer(max_features=1500)

cv=CountVectorizer()

In [31]:
X=cv.fit_transform(corpus).toarray()

In [32]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [33]:
len(sentences)

20

In [34]:
X.shape

(20, 151)

In [35]:
sentences[0]

' The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios.'

In [41]:
passage

' The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films produced by Marvel Studios. The films are based on characters that appear in American comic books published by Marvel Comics. The franchise also includes television series, short films, digital series, and literature. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters.\n\nMarvel Studios releases its films in groups called "Phases", with the first three phases collectively known as "The Infinity Saga" and the following three phases as "The Multiverse Saga". The first MCU film, Iron Man (2008), began Phase One, which culminated in the 2012 crossover film The Avengers. Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America: Civil War (2016) and concluded with Spider-Man: Far From Home (2019). Pha

In [36]:
corpus[0]

'marvel cinematic universe mcu american medium franchise shared universe centered series superhero film produced marvel studio'

In [39]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [37]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [40]:
X[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [38]:
cv.get_feature_names_out()

array(['2008', '2012', '2013', '2015', '2016', '2019', '2021', '2022',
       '2023', '2025', '2026', '2027', 'abc', 'agent', 'also', 'america',
       'american', 'ant', 'appear', 'art', 'attempt', 'attraction',
       'avenger', 'based', 'becoming', 'began', 'begin', 'beginning',
       'black', 'book', 'bugle', 'cable', 'called', 'campaign', 'captain',
       'cast', 'centered', 'character', 'cinematic', 'civil',
       'collectively', 'comic', 'commercial', 'commercially', 'common',
       'conclude', 'concluded', 'crossing', 'crossover', 'culminated',
       'daily', 'digital', 'direct', 'disney', 'element', 'end',
       'established', 'exhibit', 'expanded', 'expanding', 'fantastic',
       'far', 'faux', 'featuring', 'film', 'first', 'five', 'following',
       'forever', 'four', 'franchise', 'freeform', 'game', 'generally',
       'grossing', 'group', 'highest', 'home', 'hulu', 'includes',
       'infinity', 'inspired', 'iron', 'known', 'like', 'literary',
       'literature', 

In [ ]:
dir(cv)

In [ ]:
cv.vocabulary_

# TF-IDF

Term Frequency -Inverse Document frequency

Term Frequency =  ( No. of repetition of the word in sentence / Total No. of words in the sentence )

Inverse Document Frequency = log ( No. of sentences in the corpus /  No. of sentences containing that word ) 

for finding the exact weight: TF * IDF

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
tf=TfidfVectorizer()

In [44]:
X_tf=tf.fit_transform(corpus).toarray()

In [45]:
X_tf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.20038113,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [46]:
X_tf[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.25610913, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.29135912, 0.        , 0.29135912, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.1708386 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.23109886, 0.        , 0.        , 0.        , 0.     

In [47]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

# Word2Vec

## Bag of Words and TF IDF Problems

Both BOW and TF-IDF approach semantic information is NOT saved. 

TF-IDF gives importance to the uncommon words.

There are chances of overfitting

## Solution - Word2Vec

In this specific model, each word is basically represented as a vector of 32 or more dimension instead of a single number

Here the semantic information and relation between different words is also presereved.

In [15]:
from gensim.models import Word2Vec

#pip install gensim

In [16]:
lemma_sentences

['The Marvel Cinematic Universe ( MCU ) American medium franchise shared universe centered series superhero film produced Marvel Studios .',
 'The film based character appear American comic book published Marvel Comics .',
 'The franchise also includes television series , short film , digital series , literature .',
 'The shared universe , much like original Marvel Universe comic book , established crossing common plot element , setting , cast , character .',
 "Marvel Studios release film group called `` Phases '' , first three phase collectively known `` The Infinity Saga '' following three phase `` The Multiverse Saga '' .",
 'The first MCU film , Iron Man ( 2008 ) , began Phase One , culminated 2012 crossover film The Avengers .',
 'Phase Two began Iron Man 3 ( 2013 ) concluded Ant-Man ( 2015 ) .',
 'Phase Three began Captain America : Civil War ( 2016 ) concluded Spider-Man : Far From Home ( 2019 ) .',
 'Phase Four began Black Widow ( 2021 ) concluded Black Panther : Wakanda Foreve

In [29]:
model = Word2Vec(lemma_sentences, min_count=1)

In [30]:
model

In [31]:
words  = model.wv.vocab

AttributeError: The vocab attribute was removed from KeyedVector in Gensim 4.0.0.
Use KeyedVector's .key_to_index dict, .index_to_key list, and methods .get_vecattr(key, attr) and .set_vecattr(key, attr, new_val) instead.
See https://github.com/RaRe-Technologies/gensim/wiki/Migrating-from-Gensim-3.x-to-4

In [32]:
import random

In [33]:
random_word = random.choice(model.wv.index_to_key) 

In [34]:
random_word

'('

In [35]:
rock_idx = model.wv.key_to_index["marvel"]

KeyError: 'marvel'